version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/src/ES.Kubernetes.Reflector.Host"
  schedule:
    interval: daily
  open-pull-requests-limit: 10